# Generated by Django 5.2.7 on 2025-10-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointments_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(default='John Doe', max_length=255, verbose_name='Full name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='+254712345678', max_length=20, unique=True, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
